import sys, os
import casadi as ca
import numpy as np
from typing import Tuple,List,Optional
from datetime import datetime
import pickle

# add root to python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from utils.linear import poles_to_linear_sys
from examples.dynamics import random_linear

# SAMPLING TIME FOR DYNAMICS
TS = 0.15

# state dimension
NX = 4

# magnitude of (continuous time) poles
POLE_RANGE = (-5.0,1.0)

# horizons
HORIZON = 50

# uncertainty range
UNCERTAINTY = 1

# choose 'full' for uncertainty on the entire A and B matrices.
# choose 'poles' for uncertainty on the poles only.
MODE = 'full'

# how spread out the initial condition is
X0_MAG = 1.5

# decide whether to include noise or not
NOISE_MAG = 0.1
NOISE_SAMPLES = 500

# number of models used in robust GD
N_MODELS = 50

# whether only feasible models should be generated
FEASIBLE_ONLY = True

# upper-level cost specification (meaningful only if FEASIBLE_ONLY = True)
UPPER_LEVEL_SPECS = {'Q':10*ca.DM.eye(NX),'R':1,'x_max':15*ca.DM.ones(NX,1),'x_min':-15*ca.DM.ones(NX,1),'u_max':1,'u_min':-1}


def generate_multiple(
        sampling_time:float=0.15,
        n_x:int = 4,
        horizon:int = 20,
        n_models:int = 1,
        pole_range:Optional[Tuple[float,float]] = None,
        uncertainty:float = 1,
        x0_mag:float = 0.0,
        noise_mag:float = 0.0,
        feasible_only:bool = False,
        upper_level_specs:dict = None,
        noise_samples:int = 1,
        mode:str = 'full'
    ) -> List[dict]:
    """
    Generates a list of random linear models with specified properties.

    This function creates `n_models` random linear models, each with `n_x` states, sampled at the specified `sampling_time`.
    The models are generated with random poles within the given `pole_range` and optional pole uncertainty. The initial state
    dispersion and process noise magnitude can also be specified. Multiple noise samples can be generated by setting
    noise_samples > 1.

    If the argument "feasible_only" is set to true, then an optimal control problem is additionally solved after each
    model is generated using the information contained in the argument "upper_level_specs". If the optimal control
    problem is infeasible, then the model is not included in the list returned by this function. In this way, only models
    leading to feasible optimization problems are returned.

    The optimization problem is formulated as

        minimize_{x,u}   x^T Q x + u^T R u

        subject to       x_{t+1} = A*x_t + B*u_t,  t = 0,...,T,
                         x_min <= x_t <= x_max,    t = 0,...,T+1,
                         u_min <= u_t <= u_max,    t = 0,...,T,
                         x_0 given,
        
    where A,B are the true dynamics contained in the model, and Q,R,x_min,x_max,u_min,u_max are contained in "upper_level_specs".

    Args:
        sampling_time (float, optional): Sampling time for the models. Must be positive. Default is 0.15.
        n_x (int, optional): Number of states in each model. Must be positive. Default is 4.
        horizon (int, optional): Prediction horizon. Must be positive. Default is 20.
        n_models (int, optional): Number of models to generate. Must be positive. Default is 1.
        pole_range (Tuple[float, float], optional): Range [min, max] for the real part of the poles. Default is [-5, 1].
        uncertainty (float, optional): Uncertainty range for the system. Must be non-negative. Default is 1.
        x0_mag (float, optional): Magnitude of the initial state dispersion. Must be non-negative. Default is 0, which 
            leads to x0 = 1.
        noise_mag (float, optional): Magnitude of the process noise. Must be non-negative. Default is 0.1.
        feasible_only (bool, optional): Whether only models leading to feasible optimization problems are returned.
        upper_level_specs (dict, optional): Specifications of the optimization problem (meaningful only if feasible_only is
            set to True). It must contain the keys ['Q', 'R', 'x_min', 'x_max', 'u_min', 'u_max'] (see above for details).
        noise_samples (int, optional): Number of generated noise samples (each containing a trajectory of noise realizations).
        mode (str, optional): decides whether undertainty is applied to poles or to entire A and B matrices (possible options 
            are 'full' and 'poles', defaults to 'full').

    Returns:
        List[dict]: A list of dictionaries, each representing a generated random linear model.

    Raises:
        AssertionError: If any of the input arguments do not satisfy their constraints.

    Side Effects:
        Saves the generated models to a pickle file in the './.models/' directory. The filename includes the timestamp,
        number of states, pole range, number of models, and whether noise is present.
    """

    # default value of pole_range
    if pole_range is None:
        pole_range = [-5.0,1.0]

    assert sampling_time > 0, 'Sampling time must be positive.'
    assert n_x > 0, 'Number of states must be positive.'
    assert horizon > 0, 'Horizon must be positive.'
    assert n_models > 0, 'Number of models must be positive.'
    assert pole_range[0] <= pole_range[1], 'Pass pole_range as pole_range = [pole_min, pole_max] with pole_min <= pole_max.'
    assert uncertainty >= 0, 'Uncertainty range must be non-negative.'
    assert x0_mag >= 0, 'Dispersion of initial state must be non-negative.'
    assert noise_mag >= 0, 'Noise magnitude must be non-negative.'

    # initialize model list
    model_list = []

    # check if noise should be generated
    use_noise = noise_mag > 0
    if use_noise:
        assert noise_samples > 0, 'Number of noise samples must be strictly positive.'

    # generate n_models random linear models
    i = 0
    while i < n_models:
        
        # generate model
        model = generate_single(
                    sampling_time=sampling_time,
                    n_x=n_x,
                    pole_range=pole_range,
                    horizon=horizon,
                    uncertainty=uncertainty,
                    x0_mag=x0_mag,
                    use_noise=use_noise,
                    mode=mode
                )
        
        try:

            if feasible_only:

                consecutive_failures = 0

                # generate trajectory optimization solver if requested
                traj_solver = generate_trajectory_optimization_solver(model,upper_level_specs)

                # check if problem is feasible without noise
                best_cost,x_opti,u0 = traj_solver(model['theta_true'],model['x0'],ca.DM(model['dim']['w'],horizon)) if use_noise else traj_solver(model['theta_true'],model['x0'])

                # if cost is infinite, continue to the next model
                if best_cost == ca.inf:
                    print('cost is infinite')
                    raise Exception()

                # generate random noise if requested
                if use_noise:

                    if consecutive_failures >= 30:
                        raise Exception()

                    # initialize list containing costs
                    cost_list = []
                    cost_list_omni = [] # this one contains the cost if the noise was known in advance

                    # initialize list of noise samples
                    w_list = []

                    # initialize counter of feasible noise samples
                    done_samples = 0

                    # generate noise samples until we have generated both training and testing samples
                    while done_samples < 2*noise_samples:

                        # flag representing failure of receding horizon problem
                        receding_horizon_failed = False

                        # generate a new sample
                        sample_candidate = ( 2*np.random.rand(model['dim']['w'],horizon)-np.ones((model['dim']['w'],horizon)) ) * NOISE_MAG

                        # try to solve the trajectory optimization problem with this sample
                        cost_candidate,*_ = traj_solver(model['theta_true'],model['x0'],sample_candidate)
                        
                        # if cost is infinite, continue to the next model
                        if cost_candidate == ca.inf:
                            print('Full problem infeasible')
                            consecutive_failures += 1
                            continue

                        # if it succeeds, run in feedback to obtain best feedback cost
                        X = [model['x0']]
                        U = []
                        x_opti_t = None

                        for w_t in np.hsplit(sample_candidate,sample_candidate.shape[1]):
                            
                            # solve optimization problem
                            cost_t,x_opti_t,u_t = traj_solver(model['theta_true'],X[-1],0*sample_candidate,x_opti_t)

                            # check if problem was feasible
                            if cost_t == ca.inf:
                                # print('Receding horizon problem failed')
                                receding_horizon_failed = True
                                continue

                            # store input
                            U.append(u_t)
                                
                            # otherwise, propagate dynamics
                            X.append(model['f'](X[-1],u_t,w_t))

                        # skip if receding horizon failed
                        if receding_horizon_failed:
                            continue

                        # compute cost
                        cost_candidate_feedback = ca.vcat(X).T@ca.kron(ca.DM.eye(model['dim']['horizon']+1),upper_level_specs['Q'])@ca.vcat(X) \
                                                    + ca.vcat(U).T@ca.kron(ca.DM.eye(model['dim']['horizon']),upper_level_specs['R'])@ca.vcat(U)

                        # append cost and move on
                        cost_list.append(cost_candidate_feedback)
                        cost_list_omni.append(cost_candidate)
                        w_list.append(ca.horzsplit(sample_candidate))
                        done_samples += 1
                        print(f'Model: {i}, done samples: {done_samples}')
                
                    # divide into training and testing samples
                    model['w0'] = w_list[:noise_samples]
                    model['w0_testing'] = w_list[noise_samples:]
                    model['best_cost'] = cost_list[:noise_samples]
                    model['best_cost_omni'] = cost_list_omni[:noise_samples]
                    model['best_cost_testing'] = cost_list[noise_samples:]
                    model['best_cost_testing_omni'] = cost_list_omni[noise_samples:]
                    model['cost_spec'] = upper_level_specs

                # no noise is used, but we still need to solve the trajectory optimization problem
                else:
                    # solve the trajectory optimization problem
                    best_cost = traj_solver(model['theta_true'],model['x0'])

                    # if cost is infinite, continue to the next model
                    if best_cost == ca.inf:
                        continue

                    # add cost to model
                    model['best_cost'] = best_cost
                    model['cost_spec'] = upper_level_specs



            else:
                # if feasible_only is False, we do not need to solve the trajectory optimization problem
                # check if noise needs to be generated
                if use_noise:
                    # generate noise samples (list of lists)
                    model['w0'] = [ca.horzsplit(2*np.random.rand(model['dim']['w'],horizon)-np.ones((model['dim']['w'],horizon))) for _ in range(noise_samples)]
                    # generate testing noise samples
                    model['w0_testing'] = [ca.horzsplit(2*np.random.rand(model['dim']['w'],horizon)-np.ones((model['dim']['w'],horizon))) for _ in range(noise_samples)]
                    # add infinite cost
                    model['best_cost'] = [ca.inf]*noise_samples
                    model['best_cost_testing'] = [ca.inf]*noise_samples
                    model['cost_spec'] = None
                else:
                    model['best_cost'] = ca.inf
                    model['cost_spec'] = None

            # if the model is feasible, append it to the list
            model_list.append(model)
            i += 1
            print(f'Done: {i} out of {n_models}')

        except:
            pass

    return model_list

# generate several models and store
def generate_single(
        sampling_time:float=0.15,
        n_x:int=4,
        horizon:int=20,
        pole_range:Optional[Tuple[float,float]]=None,
        uncertainty:float=1.0,
        x0_mag:float=0.0,
        use_noise:bool=True,
        mode:str='full'
    ) -> dict:
    """
    Generates a single random linear system model with optional uncertainty and noise.
    This function creates a random linear system (e.g., for control or identification experiments)
    with specified state dimension, sampling time, and pole range. It can also introduce uncertainty
    in the system poles or matrices.

    Args:
        sampling_time (float, optional): Discretization time step for the system. Defaults to 0.15.
        n_x (int, optional): Number of states in the system. Defaults to 4.
        horizon (int, optional): Time horizon for noise realization. Defaults to 20.
        pole_range (Tuple[float, float], optional): Range for sampling the true system poles. Defaults to [-5, 1].
        uncertainty (float, optional): Magnitude of uncertainty to apply to the system. Defaults to 1.0.
        x0_mag (float, optional): Magnitude of the initial state dispersion. If equal to 0, defaults to x0 = 1.
        use_noise (bool, optional): Whether to include noise in the system dynamics. Defaults to True.
        mode (str, optional): decides whether undertainty is applied to poles or to entire A and B matrices
            (possible options are 'full' and 'poles', defaults to 'full').
    
    Returns:
        dict: A dictionary containing:
            - 'dyn_dict': Dictionary with the true system dynamics.
            - 'theta_uncertain': Parameter vector for the uncertain system.
            - 'theta_true': Parameter vector for the true system.
            - 'x0': Initial state vector.
            - 'poles_true': True system poles.
            - 'poles_uncertain': Sampled uncertain poles.
            - 'A_uncertain': State matrix of the uncertain system.
            - 'B_uncertain': Input matrix of the uncertain system.
    """

    # default values of pole_range
    if pole_range is None:
        pole_range = [-5.0, 1.0]

    # create dictionary with parameters of cart pendulum
    dyn_dict,true_theta,true_poles,mats = random_linear.dynamics(Ts=sampling_time,n_x=n_x,use_w=use_noise,pole_mag=pole_range)

    # get inputs to x_next
    func_in = [ dyn_dict[key] for key in ['x','u','w'] if key in dyn_dict ]
    func_in_names = [ key for key in ['x','u','w'] if key in dyn_dict ]

    # get inputs to x_next_nom
    func_in_nom = [ dyn_dict[key] for key in ['x','u','theta'] if key in dyn_dict ]
    func_in_names_nom = [ key for key in ['x','u','theta'] if key in dyn_dict ]

    # form x_next function
    f = ca.Function('x_next', func_in, [dyn_dict['x_next']], func_in_names, ['x_next'])

    # form x_next_nom function
    f_nom = ca.Function('x_next_nom', func_in_nom, [dyn_dict['x_next_nom']], func_in_names_nom, ['x_next_nom'])

    # set initial conditions
    x0 = ca.DM.ones(n_x,1) if x0_mag == 0 else ca.DM( x0_mag * (np.ones((n_x,1)) + 2*np.random.rand(n_x,1)) )

    if mode == 'poles':

        # create new system with uncertainty by sampling new poles within the specified uncertainty range
        poles_uncertainty = np.ones(n_x) + 2*uncertainty*np.random.rand(n_x)
        poles_uncertain = np.multiply(poles_uncertainty,true_poles)

        # apply to matrices
        A_uncertain,B_uncertain,_ = poles_to_linear_sys(poles=poles_uncertain,sampling_time=sampling_time)

    elif mode == 'full':
        
        # form uncertainty
        mat_A_uncertainty = np.ones((n_x,n_x)) + 2*uncertainty*np.random.rand(n_x,n_x)
        mat_B_uncertainty = np.ones((n_x,1)) + 2*uncertainty*np.random.rand(n_x,1)

        # apply to matrices
        A_uncertain = ca.times(mats['A'],mat_A_uncertainty)
        B_uncertain = ca.times(mats['B'],mat_B_uncertainty)

        # compute poles of nominal A matrix
        poles_uncertain = ca.DM_nan(n_x,1) #np.linalg.eig(ca.DM(A_uncertain))[0]

    else:
        raise Exception('Mode should be either poles or full.')

    # generate nominal theta
    theta0 = ca.DM(ca.vertcat(ca.vec(A_uncertain),ca.vec(B_uncertain)))

    # sample noise if requested
    if use_noise:
        # get dimension of noise
        n_w = dyn_dict['w'].shape[0]
    else:
        n_w = 0

    # save dimensions
    dim = {}
    dim['x'] = n_x
    dim['u'] = 1
    dim['w'] = n_w
    dim['horizon'] = horizon
    dim['Ts'] = sampling_time
    dim['theta'] = theta0.shape[0]

    # form output dictionary
    out_dict = {
        'f': f,
        'f_nom':f_nom,
        'theta_uncertain': theta0,
        'theta_true': true_theta,
        'x0': x0,
        'poles_true': ca.DM(true_poles),
        'poles_uncertain': ca.DM(poles_uncertain),
        'A_uncertain': ca.DM(A_uncertain),
        'B_uncertain': ca.DM(B_uncertain),
        'dim':dim
    }

    return out_dict

def generate_trajectory_optimization_solver(model:dict,upper_level_specs:dict) -> ca.Function:
    """
    Generates a CasADi optimization solver for trajectory optimization of a linear (or affine) 
    dynamical system.
    
    Args:
        model (dict): Dictionary containing model specifications. Expected keys include:
            - 'dim': Dictionary with dimensions for state ('x'), input ('u'), disturbance ('w'),
                parameter ('theta'), and 'horizon'.
            - 'x0': Initial state vector (numpy array or CasADi DM).
            - 'f_nom': Nominal dynamics function (CasADi Function) with signature f_nom(x, u, theta).
        upper_level_specs (dict): Dictionary containing upper-level cost and constraint specifications.
            Expected keys include:
            - 'Q': State cost matrix (numpy array or CasADi DM).
            - 'R': Input cost matrix (numpy array or CasADi DM).
            - 'x_max', 'x_min': State upper and lower bounds (numpy arrays or CasADi DMs).
            - 'u_max', 'u_min': Input upper and lower bounds (numpy arrays or CasADi DMs).
    Returns:
        ca.Function: CasADi function representing the trajectory optimization solver. The function
            takes as input the model parameters (theta, and optionally disturbance sequence w) and
            returns the optimal cost, the vector of optimization variables, and the first optimal
            input.
    """

    # get upper level cost
    Q = upper_level_specs['Q']
    R = upper_level_specs['R']

    # get upper level constraints
    x_max = upper_level_specs['x_max']
    x_min = upper_level_specs['x_min']
    u_max = upper_level_specs['u_max']
    u_min = upper_level_specs['u_min']

    # get opti stack
    opti = ca.Opti('conic')
    # opti = ca.Opti()

    # create optimization variables
    x = opti.variable(model['dim']['x'],model['dim']['horizon']+1)
    u = opti.variable(model['dim']['u'],model['dim']['horizon'])

    # create parameters
    x0 = opti.parameter(model['dim']['x'],1)
    if model['dim']['w'] > 0:
        w = opti.parameter(model['dim']['w'],model['dim']['horizon'])
    theta = opti.parameter(model['dim']['theta'],1)

    # enforce initial condition
    opti.subject_to( x[:,0] == x0 )

    # loop for constraints and dynamics
    for t in range(0,model['dim']['horizon']):
        
            # dynamics
            if model['dim']['w'] > 0:
                opti.subject_to( x[:,t+1] == model['f_nom'](x[:,t],u[:,t],theta) + w[:,t] )
            else:
                opti.subject_to( x[:,t+1] == model['f_nom'](x[:,t],u[:,t],theta) )

            # # test that function is correct
            # arg1 = ca.DM(np.random.rand(*x[:,t].shape))
            # arg2 = ca.DM(np.random.rand(*u[:,t].shape))
            # arg3 = ca.DM(model['dim']['w'],1)
            # assert ca.logic_all(model['f'](arg1,arg2,arg3) == model['f_nom'](arg1,arg2,model['theta_true']))

            # bound constraints
            opti.subject_to( opti.bounded(x_min, x[:,t+1], x_max) )
            opti.subject_to( opti.bounded(u_min, u[:,t], u_max) )

    # define cost
    cost =  ca.vec(x).T@ca.kron(ca.DM.eye(model['dim']['horizon']+1),Q)@ca.vec(x) \
            + ca.vec(u).T@ca.kron(ca.DM.eye(model['dim']['horizon']),R)@ca.vec(u)
    opti.minimize(cost)

    # solver
    opts = {'print_time':False,'error_on_fail':False}

    # option 1: qpOASES
    # opts['printLevel'] = 'none'
    # opti.solver('qpoases',opts)

    # option 2: osqp
    # opts['osqp'] = {"verbose":False}
    # opti.solver('osqp',opts)

    # option 3: ipopt
    # opts['ipopt'] = {"sb":'yes','print_level':0}
    # opti.solver('ipopt',opts)

    opti.solver('daqp',opts)

    # turn into function
    if model['dim']['w'] > 0:
        
        # # turn into function for speed
        # solver_compiled = opti.to_function("f",[theta,w,x0,opti.x],[cost,opti.x,u[:,0]])

        # # get shape of opti.x
        # opti_x_shape = opti.x.shape

        # def solver(theta_val,x0_val,w_val,x_opti_init=None):
        #     if x_opti_init is None:
        #         x_opti_init = 0.01*ca.DM.ones(*opti_x_shape)
        #     try:
        #         best_cost, x_out, u_out = solver_compiled(theta_val,w_val,x0_val,x_opti_init)
        #     except:
        #         best_cost = ca.inf
        #         x_out = None
        #         u_out = None

        #     return best_cost,x_out,u_out
        def solver(theta_val,x0_val,w_val,x_opti_init=None):
            opti.set_value(theta,theta_val)
            opti.set_value(w,w_val)
            opti.set_value(x0,x0_val)
            if x_opti_init is not None:
                opti.set_initial(opti.x,x_opti_init)
            # with suppress_output():

            try:
                sol = opti.solve()
                best_cost = sol.value(cost)
                x_out = sol.value(opti.x)
                u_out = sol.value(u[:,0])
            except:
                best_cost = ca.inf
                x_out = None
                u_out = None

            return best_cost,x_out,u_out
    else:
        # solver = opti.to_function("f",[theta],[cost])
        def solver(theta_val,x0_val):
            opti.set_value(theta,theta_val)
            opti.set_value(x0,x0_val)
            try:
                sol = opti.solve()
                best_cost = sol.value(cost)
                x_out = sol.value(opti.x)
                u_out = sol.value(u[:,0])
            except:
                best_cost = ca.inf
                x_out = None
                u_out = None
            return best_cost,x_out,u_out

    return solver

if __name__ == "__main__":

    # check if .models directory exists
    if not os.path.exists('./.models/'):
        os.makedirs('./.models/')
    
    # get randomly generated linear models
    models = generate_multiple(
        sampling_time=TS,
        n_x=NX,
        horizon=HORIZON,
        n_models=N_MODELS,
        pole_range=POLE_RANGE,
        uncertainty=UNCERTAINTY,
        feasible_only=FEASIBLE_ONLY,
        upper_level_specs=UPPER_LEVEL_SPECS,
        x0_mag=X0_MAG,
        noise_mag=NOISE_MAG,
        noise_samples=NOISE_SAMPLES,
        mode=MODE
    )

    # get current date and time
    formatted_date = datetime.now().strftime("%Y_%m_%d_%H_%M_%S")

    # create file name containing NX, N_MODELS and POLE_MAG and whether NOISE is present
    if NOISE_MAG > 0:
        file_name = './.models/' + formatted_date + f'_random_linear_models_NX_{NX}_POLE_MAG_{POLE_RANGE[0]}_to_{POLE_RANGE[1]}_N_MODELS_{N_MODELS}_NOISE.pkl'
    else:
        file_name = './.models/' + formatted_date + f'_random_linear_models_NX_{NX}_POLE_MAG_{POLE_RANGE[0]}_to_{POLE_RANGE[1]}_N_MODELS_{N_MODELS}.pkl'

    # dump model to file
    with open(file_name, 'wb') as file2dump:
        pickle.dump(models, file2dump)