import sys, os
import casadi as ca
import numpy as np
from typing import Tuple,List,Optional
from datetime import datetime
import pickle

# add root to python path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))

from utils.linear import poles_to_linear_sys
from examples.dynamics import random_linear

# SAMPLING TIME FOR DYNAMICS
TS = 0.15

# state dimension
NX = 4

# magnitude of (continuous time) poles
POLE_RANGE = (-5.0,1.0)

# horizons
HORIZON = 50

# uncertainty on poles
POLE_UNCERTAINTY = 4

# how spread out the initial condition is
X0_MAG = 1.5

# decide whether to include noise or not
NOISE_MAG = 0.1
NOISE_SAMPLES = 50

# number of models used in robust GD
N_MODELS = 25

# whether only feasible models should be generated
FEASIBLE_ONLY = True

# upper-level cost specification (meaningful only if FEASIBLE_ONLY = True)
UPPER_LEVEL_SPECS = {'Q':10*ca.DM.eye(NX),'R':1,'x_max':15*ca.DM.ones(NX,1),'x_min':-15*ca.DM.ones(NX,1),'u_max':1,'u_min':-1}


def generate_multiple(
        sampling_time:float=0.15,
        n_x:int = 4,
        horizon:int = 20,
        n_models:int = 1,
        pole_range:Optional[Tuple[float,float]] = None,
        pole_uncertainty:float = 1,
        x0_mag:float = 0.0,
        noise_mag:float = 0.0,
        feasible_only:bool = False,
        upper_level_specs:dict = None,
        noise_samples:int = 1
    ) -> List[dict]:
    """
    Generates a list of random linear models with specified properties.

    This function creates `n_models` random linear models, each with `n_x` states, sampled at the specified `sampling_time`.
    The models are generated with random poles within the given `pole_range` and optional pole uncertainty. The initial state
    dispersion and process noise magnitude can also be specified. Multiple noise samples can be generated by setting
    noise_samples > 1.

    If the argument "feasible_only" is set to true, then an optimal control problem is additionally solved after each
    model is generated using the information contained in the argument "upper_level_specs". If the optimal control
    problem is infeasible, then the model is not included in the list returned by this function. In this way, only models
    leading to feasible optimization problems are returned.

    The optimization problem is formulated as

        minimize_{x,u}   x^T Q x + u^T R u

        subject to       x_{t+1} = A*x_t + B*u_t,  t = 0,...,T,
                         x_min <= x_t <= x_max,    t = 0,...,T+1,
                         u_min <= u_t <= u_max,    t = 0,...,T,
                         x_0 given,
        
    where A,B are the true dynamics contained in the model, and Q,R,x_min,x_max,u_min,u_max are contained in "upper_level_specs".

    Args:
        sampling_time (float, optional): Sampling time for the models. Must be positive. Default is 0.15.
        n_x (int, optional): Number of states in each model. Must be positive. Default is 4.
        horizon (int, optional): Prediction horizon. Must be positive. Default is 20.
        n_models (int, optional): Number of models to generate. Must be positive. Default is 1.
        pole_range (Tuple[float, float], optional): Range [min, max] for the real part of the poles. Default is [-5, 1].
        pole_uncertainty (float, optional): Uncertainty range for the poles. Must be non-negative. Default is 1.
        x0_mag (float, optional): Magnitude of the initial state dispersion. Must be non-negative. Default is 0, which 
            leads to x0 = 1.
        noise_mag (float, optional): Magnitude of the process noise. Must be non-negative. Default is 0.1.
        feasible_only (bool, optional): Whether only models leading to feasible optimization problems are returned.
        upper_level_specs (dict, optional): Specifications of the optimization problem (meaningful only if feasible_only is
            set to True). It must contain the keys ['Q', 'R', 'x_min', 'x_max', 'u_min', 'u_max'] (see above for details).
        noise_samples (int, optional): Number of generated noise samples (each containing a trajectory of noise realizations).

    Returns:
        List[dict]: A list of dictionaries, each representing a generated random linear model.

    Raises:
        AssertionError: If any of the input arguments do not satisfy their constraints.

    Side Effects:
        Saves the generated models to a pickle file in the './.models/' directory. The filename includes the timestamp,
        number of states, pole range, number of models, and whether noise is present.
    """

    # default value of pole_range
    if pole_range is None:
        pole_range = [-5.0,1.0]

    assert sampling_time > 0, 'Sampling time must be positive.'
    assert n_x > 0, 'Number of states must be positive.'
    assert horizon > 0, 'Horizon must be positive.'
    assert n_models > 0, 'Number of models must be positive.'
    assert pole_range[0] <= pole_range[1], 'Pass pole_range as pole_range = [pole_min, pole_max] with pole_min <= pole_max.'
    assert pole_uncertainty >= 0, 'Pole uncertainty range must be non-negative.'
    assert x0_mag >= 0, 'Dispersion of initial state must be non-negative.'
    assert noise_mag >= 0, 'Noise magnitude must be non-negative.'
    assert noise_samples > 0, 'Number of noise samples must be strictly positive.'

    # initialize model list
    model_list = []

    # check if noise should be generated
    use_noise = noise_mag > 0

    # generate n_models random linear models
    i = 0
    while i < n_models:
        
        # generate model
        model = generate_single(
                    sampling_time=sampling_time,
                    n_x=n_x,
                    pole_range=pole_range,
                    horizon=horizon,
                    pole_uncertainty=pole_uncertainty,
                    x0_mag=x0_mag,
                    use_noise=use_noise
                )
        
        if feasible_only:

            # generate trajectory optimization solver if requested
            traj_solver = generate_trajectory_optimization_solver(model,upper_level_specs)

            # generate random noise if requested
            if use_noise:

                # initialize list containing costs
                cost_list = []

                # initialize list of noise samples
                w_list = []

                # initialize counter of feasible noise samples
                done_samples = 0

                # generate noise samples until we have generated both training and testing samples
                while done_samples < 2*noise_samples:

                    # generate a new sample
                    sample_candidate = 2*np.random.rand(model['dim']['w'],horizon)-np.ones((model['dim']['w'],horizon))

                    # try to solve the trajectory optimization problem with this sample
                    try:
                        cost_candidate = traj_solver(model['theta_true'],sample_candidate)
                    except:
                        # if it fails, continue to the next sample
                        continue

                    # if it succeeds, append to the list of costs and samples
                    cost_list.append(cost_candidate)
                    w_list.append(ca.horzsplit(sample_candidate))
                    done_samples += 1
                
                # divide into training and testing samples
                model['w0'] = w_list[:noise_samples]
                model['w0_testing'] = w_list[noise_samples:]
                model['best_cost'] = cost_list[:noise_samples]
                model['best_cost_testing'] = cost_list[noise_samples:]
                model['cost_spec'] = upper_level_specs
            
            # no noise is used, but we still need to solve the trajectory optimization problem
            else:
                # solve the trajectory optimization problem
                try:
                    best_cost = traj_solver(model['theta_true'])
                except:
                    # if it fails, continue to the next model
                    continue

                # add cost to model
                model['best_cost'] = best_cost
                model['cost_spec'] = upper_level_specs

        else:
            # if feasible_only is False, we do not need to solve the trajectory optimization problem
            # check if noise needs to be generated
            if use_noise:
                # generate noise samples (list of lists)
                model['w0'] = [ca.horzsplit(2*np.random.rand(model['dim']['w'],horizon)-np.ones((model['dim']['w'],horizon))) for _ in range(noise_samples)]
                # generate testing noise samples
                model['w0_testing'] = [ca.horzsplit(2*np.random.rand(model['dim']['w'],horizon)-np.ones((model['dim']['w'],horizon))) for _ in range(noise_samples)]
                # add infinite cost
                model['best_cost'] = [ca.inf]*noise_samples
                model['best_cost_testing'] = [ca.inf]*noise_samples
                model['cost_spec'] = None
            else:
                model['best_cost'] = ca.inf
                model['cost_spec'] = None

        # if the model is feasible, append it to the list
        model_list.append(model)
        i += 1
        print(f'Done: {i} out of {n_models}')

    return model_list

# generate several models and store
def generate_single(
        sampling_time:float=0.15,
        n_x:int=4,
        horizon:int=20,
        pole_range:Optional[Tuple[float,float]]=None,
        pole_uncertainty:float=1.0,
        x0_mag:float=0.0,
        use_noise:bool=True,
    ) -> dict:
    """
    Generates a single random linear system model with optional uncertainty and noise.
    This function creates a random linear system (e.g., for control or identification experiments)
    with specified state dimension, sampling time, and pole range. It can also introduce uncertainty
    in the system poles.

    Args:
        sampling_time (float, optional): Discretization time step for the system. Defaults to 0.15.
        n_x (int, optional): Number of states in the system. Defaults to 4.
        horizon (int, optional): Time horizon for noise realization. Defaults to 20.
        pole_range (Tuple[float, float], optional): Range for sampling the true system poles. Defaults to [-5, 1].
        pole_uncertainty (float, optional): Magnitude of uncertainty to apply to the poles. Defaults to 1.0.
        x0_mag (float, optional): Magnitude of the initial state dispersion. If equal to 0, defaults to x0 = 1.
        use_noise (bool, optional): Whether to include noise in the system dynamics. Defaults to True.
    
    Returns:
        dict: A dictionary containing:
            - 'dyn_dict': Dictionary with the true system dynamics.
            - 'theta_uncertain': Parameter vector for the uncertain system.
            - 'theta_true': Parameter vector for the true system.
            - 'x0': Initial state vector.
            - 'poles_true': True system poles.
            - 'poles_uncertain': Sampled uncertain poles.
            - 'A_uncertain': State matrix of the uncertain system.
            - 'B_uncertain': Input matrix of the uncertain system.
    """

    # default values of pole_range
    if pole_range is None:
        pole_range = [-5.0, 1.0]

    # create dictionary with parameters of cart pendulum
    dyn_dict,true_theta,true_poles = random_linear.dynamics(Ts=sampling_time,n_x=n_x,use_w=use_noise,pole_mag=pole_range)

    # get inputs to x_next
    func_in = [ dyn_dict[key] for key in ['x','u','w'] if key in dyn_dict ]
    func_in_names = [ key for key in ['x','u','w'] if key in dyn_dict ]

    # get inputs to x_next_nom
    func_in_nom = [ dyn_dict[key] for key in ['x','u','theta'] if key in dyn_dict ]
    func_in_names_nom = [ key for key in ['x','u','theta'] if key in dyn_dict ]

    # form x_next function
    f = ca.Function('x_next', func_in, [dyn_dict['x_next']], func_in_names, ['x_next'])

    # form x_next_nom function
    f_nom = ca.Function('x_next_nom', func_in_nom, [dyn_dict['x_next_nom']], func_in_names_nom, ['x_next_nom'])

    # set initial conditions
    x0 = ca.DM.ones(n_x,1) if x0_mag == 0 else ca.DM( x0_mag * (np.ones((n_x,1)) + 2*np.random.rand(n_x,1)) )

    # create new system with uncertainty by sampling new poles within the specified
    # uncertainty range
    poles_uncertain_unit = np.ones(n_x)+2*np.random.rand(n_x)
    poles_uncertain = pole_uncertainty/np.linalg.norm(poles_uncertain_unit) * poles_uncertain_unit
    A_uncertain,B_uncertain,_ = poles_to_linear_sys(poles=poles_uncertain,sampling_time=sampling_time)
    theta0 = ca.DM(ca.vertcat(ca.vec(A_uncertain),ca.vec(B_uncertain)))

    # sample noise if requested
    if use_noise:
        # get dimension of noise
        n_w = dyn_dict['w'].shape[0]
    else:
        n_w = 0

    # save dimensions
    dim = {}
    dim['x'] = n_x
    dim['u'] = 1
    dim['w'] = n_w
    dim['horizon'] = horizon
    dim['Ts'] = sampling_time
    dim['theta'] = theta0.shape[0]

    # form output dictionary
    out_dict = {
        'f': f,
        'f_nom':f_nom,
        'theta_uncertain': theta0,
        'theta_true': true_theta,
        'x0': x0,
        'poles_true': ca.DM(true_poles),
        'poles_uncertain': ca.DM(poles_uncertain),
        'A_uncertain': ca.DM(A_uncertain),
        'B_uncertain': ca.DM(B_uncertain),
        'dim':dim
    }

    return out_dict

def generate_trajectory_optimization_solver(model:dict,upper_level_specs:dict) -> ca.Function:
    """
    Generates a CasADi optimization solver for trajectory optimization of a linear (or affine) 
    dynamical system.
    
    Args:
        model (dict): Dictionary containing model specifications. Expected keys include:
            - 'dim': Dictionary with dimensions for state ('x'), input ('u'), disturbance ('w'),
                parameter ('theta'), and 'horizon'.
            - 'x0': Initial state vector (numpy array or CasADi DM).
            - 'f_nom': Nominal dynamics function (CasADi Function) with signature f_nom(x, u, theta).
        upper_level_specs (dict): Dictionary containing upper-level cost and constraint specifications.
            Expected keys include:
            - 'Q': State cost matrix (numpy array or CasADi DM).
            - 'R': Input cost matrix (numpy array or CasADi DM).
            - 'x_max', 'x_min': State upper and lower bounds (numpy arrays or CasADi DMs).
            - 'u_max', 'u_min': Input upper and lower bounds (numpy arrays or CasADi DMs).
    Returns:
        ca.Function: CasADi function representing the trajectory optimization solver. The function
            takes as input the model parameters (theta, and optionally disturbance sequence w) and
            returns the optimal cost.
    """

    # get upper level cost
    Q = upper_level_specs['Q']
    R = upper_level_specs['R']

    # get upper level constraints
    x_max = upper_level_specs['x_max']
    x_min = upper_level_specs['x_min']
    u_max = upper_level_specs['u_max']
    u_min = upper_level_specs['u_min']

    # get opti stack
    opti = ca.Opti()

    # create optimization variables
    x = opti.variable(model['dim']['x'],model['dim']['horizon']+1)
    u = opti.variable(model['dim']['u'],model['dim']['horizon'])

    # create parameters
    if model['dim']['w'] > 0:
        w = opti.parameter(model['dim']['w'],model['dim']['horizon'])
    theta = opti.parameter(model['dim']['theta'],1)

    # enforce initial condition
    opti.subject_to( x[:,0] == model['x0'] )

    # loop for constraints and dynamics
    for t in range(0,model['dim']['horizon']):
        
            # dynamics
            if model['dim']['w'] > 0:
                opti.subject_to( x[:,t+1] == model['f_nom'](x[:,t],u[:,t],theta) + w[:,t] )
            else:
                opti.subject_to( x[:,t+1] == model['f_nom'](x[:,t],u[:,t],theta) )

            # # test that function is correct
            # arg1 = ca.DM(np.random.rand(*x[:,t].shape))
            # arg2 = ca.DM(np.random.rand(*u[:,t].shape))
            # arg3 = ca.DM(model['dim']['w'],1)
            # assert ca.logic_all(model['f'](arg1,arg2,arg3) == model['f_nom'](arg1,arg2,model['theta_true']))

            # bound constraints
            opti.subject_to( opti.bounded(x_min, x[:,t+1], x_max) )
            opti.subject_to( opti.bounded(u_min, u[:,t], u_max) )

    # define cost
    cost =  ca.vec(x).T@ca.kron(ca.DM.eye(model['dim']['horizon']+1),Q)@ca.vec(x) \
            + ca.vec(u).T@ca.kron(ca.DM.eye(model['dim']['horizon']),R)@ca.vec(u)
    opti.minimize(cost)

    # solver
    opts = dict()
    opts["print_time"] = False
    opts['ipopt'] = {"print_level": 0, "sb":'yes'}
    # opts['error_on_fail'] = True
    opti.solver('ipopt',opts)

    # turn into function
    if model['dim']['w'] > 0:
        # solver = opti.to_function("f",[theta,w],[cost])
        def solver(theta_val,w_val):
            opti.set_value(theta,theta_val)
            opti.set_value(w,w_val)
            try:
                opti.solve()
                best_cost = opti.value(cost)
            except:
                best_cost = ca.inf
            return best_cost
    else:
        # solver = opti.to_function("f",[theta],[cost])
        def solver(theta_val):
            opti.set_value(theta,theta_val)
            opti.solve()
            return opti.value(cost)

    return solver

if __name__ == "__main__":

    # check if .models directory exists
    if not os.path.exists('./.models/'):
        os.makedirs('./.models/')
    
    # get randomly generated linear models
    models = generate_multiple(
        sampling_time=TS,
        n_x=NX,
        horizon=HORIZON,
        n_models=N_MODELS,
        pole_range=POLE_RANGE,
        pole_uncertainty=POLE_UNCERTAINTY,
        feasible_only=FEASIBLE_ONLY,
        upper_level_specs=UPPER_LEVEL_SPECS,
        x0_mag=X0_MAG,
        noise_mag=NOISE_MAG,
        noise_samples=NOISE_SAMPLES
    )

    # get current date and time
    formatted_date = datetime.now().strftime("%Y_%m_%d_%H_%M_%S")

    # create file name containing NX, n_modelN_MODELSs and POLE_MAG and whether NOISE is present
    if NOISE_MAG > 0:
        file_name = './.models/' + formatted_date + f'_random_linear_models_NX_{NX}_POLE_MAG_{POLE_RANGE[0]}_to_{POLE_RANGE[1]}_N_MODELS_{N_MODELS}_NOISE.pkl'
    else:
        file_name = './.models/' + formatted_date + f'_random_linear_models_NX_{NX}_POLE_MAG_{POLE_RANGE[0]}_to_{POLE_RANGE[1]}_N_MODELS_{N_MODELS}.pkl'

    # dump model to file
    with open(file_name, 'wb') as file2dump:
        pickle.dump(models, file2dump)